
package BOVSite;

import EmployeeSite.CEmpMain;
import EmployeeSite.DodEmpMain;
import EmployeeSite.FordEmpMain;
import EmployeeSite.TEmpMain;
import ManufactureSite.CMainMenu;
import ManufactureSite.DodMainMenu;
import ManufactureSite.FordMainMenu;
import ManufactureSite.TMainMenu;
import jIntro.unameErr;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;


public class CarViewEmp extends javax.swing.JFrame {
    
    private String company = "";

    /**
     * Creates new form CarView
     */
    public CarViewEmp() {
        initComponents();
    }
    
    public CarViewEmp(String comp){
        setCompany(comp);
        initComponents();
    }
    
    public String getCompany(){
        return this.company;
    }
    
    public void setCompany(String val){
        this.company = val;
    }
    
    private Object[][] getData(){
        List<String[]> res = new ArrayList<String[]>();
        Connection c = null;
        Statement stmt = null;
        try {
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:bov.bak2.db");
            c.setAutoCommit(false);
            System.out.println("Opened database successfully");
            stmt = c.createStatement();
            String comp = company;
            String q = "";
            if(comp == null){
                q = "SELECT * FROM vehicles";
            } else {
                q = "SELECT * FROM vehicles WHERE make='" + comp + "';";
            }
            System.out.println(q);
            ResultSet rs = stmt.executeQuery(q);
            while(rs.next()){
                String[] row = {"", "", "", "", "", ""};
                row[0] = String.valueOf(rs.getInt("year"));
                row[1] = rs.getString("make");
                row[2] = rs.getString("model");
                row[3] = rs.getString("gas");
                row[4] = rs.getString("color");
                res.add(row);
            }
            rs.close();
            stmt.close();
            c.commit();
            c.close();
            Object[][] dArray = new Object[res.size()][5];
            for (int i = 0; i < res.size(); i++){
                for(int e = 0; e < 5; e ++){
                    dArray[i][e] = res.get(i)[e];
                }
            }
            return dArray;
        } catch ( Exception e ) {
          System.err.println( e.getClass().getName() + ": " + e.getMessage() );
          System.exit(0);
          return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleStringLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        carTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleStringLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleStringLabel.setText("List of Vehicles for Automotive Company");
        titleStringLabel.setAlignmentX(0.5F);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        Object[][] rows;
        if(this.company != null){
            rows = getData();
        } else {
            rows = new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            };
        }
        carTable.setModel(new javax.swing.table.DefaultTableModel(
            rows,
            new String [] {
                "Year", "Make", "Model", "Feul Economy", "Color"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        carTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(carTable);
        if (carTable.getColumnModel().getColumnCount() > 0) {
            carTable.getColumnModel().getColumn(0).setResizable(false);
            carTable.getColumnModel().getColumn(1).setResizable(false);
            carTable.getColumnModel().getColumn(2).setResizable(false);
            carTable.getColumnModel().getColumn(3).setResizable(false);
            carTable.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(backButton))
                    .addComponent(titleStringLabel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleStringLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        Connection c = null;
        Statement stmt = null;
    try {
      Class.forName("org.sqlite.JDBC");
      c = DriverManager.getConnection("jdbc:sqlite:bov.db");
      c.setAutoCommit(false);
      System.out.println("Opened database successfully");
      stmt = c.createStatement();
      ResultSet rs = stmt.executeQuery("SELECT company,here,admin FROM users WHERE here = 'here';");
      while(rs.next()){
          if (rs.getString("company").equals("Chevy") && rs.getString("admin").equals("admin")){
              new CMainMenu().setVisible(true);
              this.dispose();
      
          }
          else if (rs.getString("company").equals("Ford") && rs.getString("admin").equals("admin")){
              new FordMainMenu().setVisible(true);
              this.dispose();
          }
          else if (rs.getString("company").equals("Dodge") && rs.getString("admin").equals("admin")){
              new DodMainMenu().setVisible(true);
              this.dispose();
          }
          else if (rs.getString("company").equals("Toyota") && rs.getString("admin").equals("admin")){
              new TMainMenu().setVisible(true);
              this.dispose();
          }
          else if (rs.getString("company").equals("BOV")){
              new VehicleForm().setVisible(true);
              this.dispose();
          }
          else if (rs.getString("company").equals("Chevy") && rs.getString("admin").equals("empl")){
              new CEmpMain().setVisible(true);
              this.dispose();
          }
          else if (rs.getString("company").equals("Ford") && rs.getString("admin").equals("empl")){
              new FordEmpMain().setVisible(true);
              this.dispose();
          }
          else if (rs.getString("company").equals("Dodge") && rs.getString("admin").equals("empl")){
              new DodEmpMain().setVisible(true);
              this.dispose();
          }
          else if (rs.getString("company").equals("Toyota") && rs.getString("admin").equals("empl")){
              new TEmpMain().setVisible(true);
              this.dispose();
          }
      }
      
      //new unameErr().setVisible(true);
      rs.close();
      stmt.close();
      c.commit();
      c.close();
    } catch ( Exception e ) {
      System.err.println( e.getClass().getName() + ": " + e.getMessage() );
      System.exit(0);// TODO add your handling code here:
    }// TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarViewEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarViewEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarViewEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarViewEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarViewEmp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTable carTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel titleStringLabel;
    // End of variables declaration//GEN-END:variables
}
